"""V4__image_column_created

Revision ID: 1051e5011026
Revises: 2dd80a36b58f
Create Date: 2024-11-19 11:00:46.928995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1051e5011026'
down_revision = '2dd80a36b58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
